# See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows

name: cron-jobs
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
env:
  GH_CRON_API_KEY: ${{ secrets.GH_CRON_API_KEY }}
jobs:
  cron-closeDayOrders:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        shell: bash
        # if: github.event.schedule == '0 9 * * *'
        run: |
          curl --location --request POST 'http://179.158.238.68:3000/api/graphql' \
          --header 'GH_CRON_API_KEY: ${{ env.GH_CRON_API_KEY }}' \
          --header 'x-access-origin: GithubCron' \
          --header 'Content-Type: application/json' \
          --data-raw '{"query":"mutation {\n    CloseDayOrders\n}","variables":{}}'
      - name: show
        run: |
          echo teste: $GH_CRON_API_KEY
      - name: show 2
        run: |
          echo 'teste: ${{ toJSON(github) }}'

