# See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows

name: cron-jobs
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
env:
  GH_CRON_API_KEY: '${{ secrets.GH_CRON_API_KEY }}'
  EVENT_NAME: '${{ github.event.name }}'
jobs:
  cron-closeDayOrders:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        shell: bash
        if: github.event.schedule == '0 9 * * *'
        run: |
          curl --location --request POST 'https://truegifter.com/api/graphql' \
          --header 'GH_CRON_API_KEY: $GH_CRON_API_KEY' \
          --header 'x-access-origin: GithubCron' \
          --header 'Content-Type: application/json' \
          --data-raw '{"query":"mutation {\n    CloseDayOrders\n}","variables":{}}'
      - name: show
        run: |
          echo 'teste: $EVENT_NAME'
