name: merge-sql-files
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge SQL Files
        run: cd sql && ./merge-sql-files.sh
      - name: Commit report
        run: |
          git config --global user.name 'hugo miranda'
          git config --global user.email 'hugo.miranda.souza@gmail.com'
          git commit -am "merge-sql-files-action"
          git push